name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        buildtype: [windows-latest, windows-latest (clangcl), windows-2016, ubuntu-latest, macOS-latest]
        include:
        - buildtype: windows-latest
          os: windows-latest
          generator: '"Visual Studio 16 2019"'
        - buildtype: windows-latest (clangcl)
          os: windows-latest
          generator: '"Visual Studio 16 2019" -T "clangcl"'
        - buildtype: windows-2016
          os: windows-2016
          generator: '"Visual Studio 15 2017"' 
        - buildtype: ubuntu-latest
          os: ubuntu-latest
          generator: '"Unix Makefiles"'
        - buildtype:  macOS-latest
          os: macOS-latest
          generator: '"Unix Makefiles"'  
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - name: cmake
      run: cmake -G ${{ matrix.generator }}
    - name: build
      run: cmake --build .
    - name: test
      run: ctest --verbose --parallel 4 -C Debug
